image: "debian:buster"

build:
  stage: build
  before_script:
    - apt update && apt install cpio abootimg debootstrap pbuilder -y
    - mv /usr/share/debootstrap/functions /tmp/debootstrap-functions
    - sed 's/^.*umount "$TARGET\/proc".*$//' /tmp/debootstrap-functions > /usr/share/debootstrap/functions
  script:
    - pbuilder create --distribution buster
    - cp allpkgs.config .config
    - make packages
  artifacts:
    paths:
      - '*.deb'
pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r docs/* .public
    - mkdir .public/packages-latest
    - cp *.deb .public/packages-latest/
    - mv .public public
  artifacts:
    paths:
      - public
  dependencies:
    - build
  only:
    - stable
