image: "debian:bullseye"

build:
  stage: build
  before_script:
    - apt update && apt install cpio abootimg debootstrap pbuilder qemu-user-static -y
    - sed -i 's/^.*umount "$TARGET\/proc".*$//' /usr/share/debootstrap/functions
  script:
    - pbuilder create --distribution bullseye
    - cp allpkgs.config .config
    - mount
    - make USE_QEMU=1
  artifacts:
    paths:
      - '*.deb'
      - boot.img
      - debroot.tar
  interruptible: true

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r docs/* .public
    - mkdir .public/packages-latest
    - cp *.deb .public/packages-latest/
    - mv .public public
  artifacts:
    paths:
      - public
  dependencies:
    - build
  only:
    - stable
