image: "debian:buster"

build:
  stage: build
  before_script:
    - apt update && apt install cpio abootimg debootstrap pbuilder -y
    - mv /usr/share/debootstrap/functions /tmp/debootstrap-functions
    - sed 's/^.*umount "$TARGET\/proc".*$//' /tmp/debootstrap-functions > /usr/share/debootstrap/functions
    - git clone $CI_SERVER_URL/$CI_PROJECT_NAMESPACE/bananui-base
    - git clone $CI_SERVER_URL/$CI_PROJECT_NAMESPACE/device-startup-8110 device-startup
    - git clone $CI_SERVER_URL/$CI_PROJECT_NAMESPACE/libbananui
  script:
    - pbuilder create --distribution buster
    - make bananui-base_$(make getversion)_armhf.deb
    - make device-startup_$(make getversion)_all.deb
    - echo "PACKAGE_VERSION=$(make getversion)" > version.env
  artifacts:
    reports:
      dotenv: version.env
    paths:
      - bananui-base_*_armhf.deb
      - device-startup_*_all.deb
      # There is no underscore before the * to include libbananui0-dev
      - libbananui0*_armhf.deb
  only:
    - stable
pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r docs/* .public
    - mkdir .public/packages-latest
    - cp bananui-base_${PACKAGE_VERSION}_armhf.deb .public/packages-latest/
    - cp device-startup_${PACKAGE_VERSION}_all.deb .public/packages-latest/
    - cp libbananui0*${PACKAGE_VERSION}_armhf.deb .public/packages-latest/
    - mv .public public
  artifacts:
    paths:
      - public
  dependencies:
    - build
  only:
    - stable

packages:
  stage: deploy
  before_script:
    - apt update && apt install curl -y
  script:
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file bananui-base_${PACKAGE_VERSION}_armhf.deb ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/bananui-base/${PACKAGE_VERSION}/bananui-base_${PACKAGE_VERSION}_armhf.deb'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file device-startup_${PACKAGE_VERSION}_all.deb ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/device-startup/${PACKAGE_VERSION}/device-startup_${PACKAGE_VERSION}_all.deb'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file libbananui0_${PACKAGE_VERSION}_armhf.deb ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/libbananui0/${PACKAGE_VERSION}/libbananui0_${PACKAGE_VERSION}_armhf.deb'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file libbananui0-dev_${PACKAGE_VERSION}_armhf.deb ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/libbananui0-dev/${PACKAGE_VERSION}/libbananui0-dev_${PACKAGE_VERSION}_armhf.deb'
  dependencies:
    - build
  only:
    - stable
