#!/sbin/sh

export PATH=/sbin
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mount -t ext4 /dev/mmcblk1p2 /root
mkdir -p /root/var/log/bananian/
exec /init.logged >/root/var/log/bananian/boot.log 2>&1
echo 'bananian-init: FATAL: failed to exec init.logged' >/root/var/log/bananian/boot.log
