#!/sbin/sh
export PATH=/sbin
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mount -t ext4 /dev/mmcblk1p2 /root
mount -t devtmpfs devtmpfs /root/dev
mount -t sysfs sysfs /root/sys
mount -t procfs procfs /root/proc
exec run-init /root /sbin/init $@
